### ISSUE TITLE
Call to undefined function

### ISSUE THREAD

**Issue by john-arvid** [mizunashi-mana/dokuwiki-plugin-mdpage#57]
**This is a bug report.**

| Name | Value |
| --- | --- |
| DokuWiki Version | 2018-04-22c |
| PHP Version | 7.3.18 |
| OS | Linux/Docker |
| Web Server | nginx/1.16.1 |

Details:
Not sure if this has something to do with the docker image I am using, either way I would like to find a solution.

Using dokuwiki on docker. [https://hub.docker.com/r/linuxserver/dokuwiki](https://hub.docker.com/r/linuxserver/dokuwiki)

Just started it up and created a few pages. 
Installed the mdpage plugin with the extension manager.
Tried to add the example block from the readme.
Get this in the nginx error log:

```
2020/06/12 19:33:21 [error] 349#349: *1 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function cebe\markdown\ctype_alpha() in /config/dokuwiki/lib/plugins/mdpage/vendor/cebe/markdown/GithubMarkdown.php:69
Stack trace:
#0 /config/dokuwiki/lib/plugins/mdpage/vendor/cebe/markdown/Parser.php(195): cebe\markdown\GithubMarkdown->consumeParagraph(Array, 3)
#1 /config/dokuwiki/lib/plugins/mdpage/vendor/cebe/markdown/Parser.php(170): cebe\markdown\Parser->parseBlock(Array, 3)
#2 /config/dokuwiki/lib/plugins/mdpage/vendor/cebe/markdown/Parser.php(60): cebe\markdown\Parser->parseBlocks(Array)
#3 /config/dokuwiki/lib/plugins/mdpage/src/DokuWiki/Plugin/Mdpage/MarkdownRendererTrait.php(22): cebe\markdown\Parser->parse('\n# Header\n\nsimp...')
#4 /config/dokuwiki/lib/plugins/mdpage/src/DokuWiki/Plugin/Mdpage/Markdown.php(28): DokuWiki\Plugin\Mdpage\Markdown\GitHubFlavored->parseOnce('\n# Header\n\nsimp...')
#5 /config/dokuwiki/lib/plugins/mdpage/syntax.php(75): DokuWiki\Plugin\Mdpage\Markdown::parseWithRenderer(Object(Doku_Renderer_" while reading upstream, client: 192.168.1.10, server: _, request: "POST /wiki/docker?do=edit HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "192.168.1.16:8080", referrer: "http://192.168.1.16:8080/wiki/docker?do=edit"

```

**Comment by mmarquezs** [comment]
Hi, I had the same issue today. The plugin requires the extension ctype to be available. 
Usually ctype is included by default but that's not the case in the linuxserver/dokuwiki image. It might be a good idea to open a bug there because I think it's a pretty common library to use but maybe I'm wrong.

You can check it this way, connecting to the container and installing the extension. Since is based on alpine you can install it with "apk add php-ctype" and then restart the container. 
You will see that now it works, I think I had some pages not showing due to cache but after a hard refresh it worked. 

For a more permanent solution you will have to make a new image based on that one that includes the install of php-ctype. Alternatively there is this other image that includes ctype: https://hub.docker.com/r/bitnami/dokuwiki/ 
But... I was using that image until today when somehow after an update to the latests image it broke.... and I switched to the linuxserver because they are usually good and I'm using them for other apps.

**Comment by john-arvid** [comment]
Created the issue over at linuxserver. Check that out to see what the solution will be.

**Comment by mizunashi-mana** [comment]
@john-arvid Thanks for report, and @mmarquezs Thanks for details and solutions.

I researched this problem and found DokuWiki can run without ctype extensions.
So, I resolve this problem in this plugin with symfony polyfills.
Please, wait new release.

**Comment by mizunashi-mana** [comment]
I published the new release.  Please update.

**Comment by mmarquezs** [comment]
Oh nice I didn't even knew there was polyfills in php. 
I just updated and working fine without ctype, thanks for the update! 👍
